### ISSUE TITLE
Internal 500 error on multi POSTs

### ISSUE THREAD

**Issue by ksred** [visa/SampleCode#13]
I am busy writing a package for the Visa Developer API in Go: https://github.com/ksred/visa. When doing Multi POST requests, a 500 internal server error is returned.

The below data is for PullFundsTransactionMultiPost.

*Request*

```
{"localTransactionDateTime":"2016-04-16T08:34:45","acquiringBin":409999,"acquirerCountryCode":101,"businessApplicationId":"AA","merchantCategoryCode":6012,"request":[{"localTransactionDateTime":"2016-04-16T08:34:45","systemsTraceAuditNumber":123456,"retrievalReferenceNumber":"407509300259","senderPrimaryAccountNumber":"4957030100009952","senderCardExpiryDate":"2020-03","senderCurrencyCode":"USD","amount":110,"cavv":"0000010926000071934977253000000000000000","cardAcceptor":{"name":"Saranya","terminalId":"365539","idCode":"VMT200911026070","address":{"state":"CA","county":"081","country":"USA","zipCode":"94404"}}},{"localTransactionDateTime":"2016-04-16T08:34:45","systemsTraceAuditNumber":123456,"retrievalReferenceNumber":"407509300259","senderPrimaryAccountNumber":"4957030100009952","senderCardExpiryDate":"2020-03","senderCurrencyCode":"USD","amount":110,"cavv":"0000010926000071934977253000000000000000","cardAcceptor":{"name":"Saranya","terminalId":"365539","idCode":"VMT200911026070","address":{"state":"CA","county":"081","country":"USA","zipCode":"94404"}}}]}
```

*Response*

```
	VisaDirect_test.go:352: Error when getting response: HTTP error: 500 Internal Server Error, <?xml version='1.0' ?>
		<env:Envelope xmlns:env='http://schemas.xmlsoap.org/soap/envelope/'>
		<env:Body>
		<env:Fault>
		<faultcode>env:Client</faultcode>
		<faultstring>Internal Error</faultstring>
		</env:Fault>
		</env:Body>
		</env:Envelope>
```

This happens on all multi posts:

- PullFundsTransactionMultiPost
- PushFundsTransactionMultiPost
- ReverseFundsTransactionMultiPost

I can't see anything wrong with the data that I am sending. Regardless of my data integrity, a 500 should not be returned.

**Comment by hemanthmanoharan** [comment]
Thanks for your interest in building a 'Go' package for Visa Developer API. We are currently investigating the issue you have reported and will get back to you in a day or two.

**Comment by hemanthmanoharan** [comment]
@ksred We investigated into the issue and have found the following suggestions to make your code work. The Multi-POST calls need to have the `Accept` header value as `application/octet-stream` only. This is a documentation fix that we will update in our Portal as well. We also acknowledge that the 500 error code is not the right one to return in such scenarios. We will fix that behavior as well.

Also, the `X-Client-Transaction-ID` header for the Multi-POST calls needs to be an unique identifier. Re-using the same static value across calls will result in errors. You could use some guid-library like, for example, `github.com/nu7hatch/gouuid` to generate an unique value for each call. 
 
Do let us know if these two changes make the calls succeed at your end.

**Comment by ksred** [comment]
@hemanthmanoharan Thanks for this explanation, all tests now run successfully. The UUID has been implemented in all calls, thank you for that additional information.

Might I suggest that all calls follow a standard? Ideally, I would like to send `application/json` on all requests and not have to switch for certain cases. As you can see the implementation of this is quite hacky:

```
switch acceptType {
case "octet-stream":
	req.Header.Set("Accept", "application/octet-stream")
case "json":
	req.Header.Set("Accept", "application/json")
}
```

I'm not sure what the reasoning behind this is, but the new fix leads all tests to pass correctly. Thanks for the assist!
