### ISSUE TITLE
The Java version having issue for token generated.

### ISSUE THREAD

**Issue by FadiZeng** [visa/SampleCode#16]
The token generated were uppercase, this would cause the transaction failed with "Token verification Failed". To fix this issue, please convert the token to lower case, then it will works.
	/**
	 * Generate X-Pay-Token as x:+ TimestampUTC + : + SHA256Hash
	 * 
	 * @param payload
	 * @param uri
	 * @param apiKey
	 * @param sharedSecret
	 * @return
	 * @throws SignatureException
	 */
	public static String generateXpaytoken(String payload, String uri, String apiKey, String sharedSecret) throws SignatureException {
		System.out.println(uri);
		String timestamp = timeStamp();
		String beforeHash = timestamp + uri + "apikey=" + apiKey + payload;
		String hash = hmacSha256Digest(beforeHash, sharedSecret);
		String token = "xv2:" + timestamp + ":" + hash;
		return token.toLowerCase();//Modify this
	}

**Comment by hemanthmanoharan** [comment]
@FadiZeng Thanks for pointing out this issue in our sample code. We will get this addressed in our next code push.

**Comment by VisaDeveloperProgram** [comment]
This is fixed in the latest code push.
