### ISSUE TITLE
How to create the P12 file required for Visa Direct sample code?

### ISSUE THREAD

**Issue by gauravmokhasi** [visa/SampleCode#17]
In SampleCode/SampleCode/VisaAPICalls/C#/visadirect/VisaDirectSample.cs, the following lines ask you to generate a P12 file according to a README. 
<code>
// P12 File settings
</code>
<code>
// Follow instructions in README for generating P12 file
</code>
<code>
private static string P12_FILE_PATH = @"{put the path to the P12 file here}";
</code>
<code>
private static string P12_FILE_PASSWORD = @"{put the P12 file password}";
</code>
Which README is it referring to? SampleCode/README.md doesn't seem to have anything around this. When you create a test Visa direct app from VDP, you get a .pem file. How to convert this to P12?

**Comment by Sguptavisa** [comment]
Hi,
You have to look for  README.md file in "SampleCode/SampleCode/VisaAPICalls/C#" directory.

**Comment by gauravmokhasi** [comment]
Thanks Saurabh :+1:
