### ISSUE TITLE
cant set private key. . . error

### ISSUE THREAD

**Issue by thom7kick** [visa/SampleCode#21]

**Comment by thom7kick** [comment]
here is the sample error
  <strong>URL:</strong>

> <br>https://sandbox.api.visa.com/visadirect/fundstransfer/v1/pullfundstransactions<br><br>Error: "unable to set private key file: 'VZVQ1BQQWRDOQD49L2JL21**************' type PEM"

**Comment by hemanthmanoharan** [comment]
@thom7kick Thanks for reaching out to us. Could you please provide us the following details on the issue to help us debug it faster
- Which programming language are you using to make the API call? From a quick search of the error on the net, it seems it is PHP. But it would be great if you can confirm the same.
- If using PHP, Could you please give us details around the OS, php and curl version that you are using.

**Comment by thom7kick** [comment]
@hemanthmanoharan i am using: i am using php, curl version curl 7.47.0, linux OS.
The issue was i had the wrong certificate path. i am past that issue now. now dealing with the following error: 
` "errorMessage": "API Validation Error: 3001. Mandatory field 'localTransactionDateTime' is missing or has invalid content."
`

**Comment by mmodi-visa** [comment]
@thom7kick Thanks for the patience. From the error which you are seeing, the possible reason can be that the data being passed in 'localTransactionDateTime' is in incorrect format. 

For PHP you can get the localTransactionDateTime using date('Y-m-d\TH:i:s', time()) 

Please try to get the time in the above stated format and try calling the API again to see if you face the same issue. 

Thanks.

**Comment by vaseemansari007** [comment]
Hi

The below apikey used in sample code to show visa checkout button.
apikey: "7O07VN664O10JW6A9ESS113p8sf9JeGzr6_2haC9F9m_ANtLM",

I am getting error when i am replacing this key with mine (generated from https://developer.visa.com/portal using create new application)

This is the error. {"responseStatus":{"code":"9005","severity":"ERROR","info":"http://api.visa.com/docs/errors/9005","status"
:401,"message":"Invalid ApiKey"}}

Please let me know if i have generated a wrong key or do i need to allow localhost ip in the developer account or any other solution.

**Comment by mmodi-visa** [comment]
@vaseemansari007 Thanks for reaching out. You can check for the status of the app and whether it was activated correctly. Also make sure that the apiKey which you are using is in ACTIVE status. 
You will be able to view your apiKey in the left nav bad under **Keys / APIs**
 
If the apiKey is active and is registered for Visa Checkout but you are still facing the issue, please share the code with us to help debug faster.

**Comment by mmodi-visa** [comment]
@thom7kick  @vaseemansari007 Hoping that we were able to assist you in solving your issues.  If you were able to move forward and make successful api calls we would like to close this open issue. Thanks for using Visa API's.

**Comment by thom7kick** [comment]
you can close it @mmodi-visa

**Comment by mmodi-visa** [comment]
Thanks @thom7kick 
Hope You had a good experience using Visa API's.
