### ISSUE TITLE
Visa Merchant Offers Data API responding "Invalid URI"

### ISSUE THREAD

**Issue by sayandev** [visa/SampleCode#29]
Hi, 

I am tryinbg to use the Visa Merchant Offers Data API following the documenation given in:
https://developer.visa.com/products/vmorc/reference#vmorc
For all of the categories: Retrieve Offers By Offer Id; Retrieve Offers By Content Id; Retrieve Offers By Filter and Retrieve All Offers I am getting the response status code 404, "Invalid URI". 

![image](https://cloud.githubusercontent.com/assets/3611781/18959617/d65232de-8634-11e6-8b10-1196d7eaa14c.png)

I am attaching the python code I am using. Any suggestion will be highly aappreciated to make the PAI call work accordingly.

########################################################
import json
import requests

user_id = 'AZP29ZAILMIJQ4YFGQ3M21R0QnnV1_Qy-ZhrCHDPLlT-MjkrA'
password = '1LA4R5rGGK5vymUsp75JAVHprEjGlAgH'

headers = {'content-type': 'application/json', 'accept':'application/json'}
body='''{
}'''

base_uri = 'vmorc/offers/'
resource_path = 'v1/all/'
url = 'https://sandbox.api.visa.com/' + base_uri + resource_path

r = requests.post(url,
  cert = ('cert.pem','privateKey.pem'),
  headers = headers,
  auth = (user_id, password),
  data = body)
  
  # Print the response
print r.status_code
data=json.loads(r.content)

###########################################################

**Comment by mmodi-visa** [comment]
@sayandev Thanks for reaching out to us. The end point you are trying to call is a get endpoint and you are making a post call. The code below show work fine for you 

import json
import requests

user_id = 'AZP29ZAILMIJQ4YFGQ3M21R0QnnV1_Qy-ZhrCHDPLlT-MjkrA'
password = '1LA4R5rGGK5vymUsp75JAVHprEjGlAgH'

headers = {'content-type': 'application/json', 'accept':'application/json'}
body='''{
}'''

base_uri = 'vmorc/offers/'
resource_path = 'v1/all/'
url = 'https://sandbox.api.visa.com/' + base_uri + resource_path

r = requests.get(url,
cert = ('cert.pem','privateKey.pem'),
headers = headers,
auth = (user_id, password))

print r.status_code
data=json.loads(r.content)

**Comment by sayandev** [comment]
@mmodi-visa Thanks a lot for your detailed response. I really appreciate it. Have a great weekend.
