### ISSUE TITLE
Bug in Python Client

### ISSUE THREAD

**Issue by dborstelmann** [visa/SampleCode#37]
You are missing a header on GET requests in the mutual_auth function that causes requests to return "unsupported media type"

https://github.com/visa/SampleCode/blob/master/vdp-python/visa/helpers/visa_api_client.py#L81

You need the content-type header to be application/json.

**Comment by ankeshanand** [comment]
Fixed in https://github.com/visa/SampleCode/commit/382fb13d89b057bb85aa8ed400d46eee2fa3a567
