### ISSUE TITLE
API Validation Error: 3001.

### ISSUE THREAD

**Issue by YuriiZadorozhnyi** [visa/SampleCode#42]
I have this error just using original code from: https://github.com/visa/SampleCode/ 
I made all instructions from video on youtube: https://www.youtube.com/watch?v=O9imTyZT6Co 
But still have this error: 

Body: {
    "errorMessage": "API Validation Error: 3001. Transaction to Recipient Card Country is restricted by the Sender Institution "
}
    1) Push Funds Transaction Test

## **All terminal information:** 

Visa Direct Push Funds Transactions test
URL : https://sandbox.api.visa.com/visadirect/fundstransfer/v1/pushfundstransactions
Request Body : {
    "systemsTraceAuditNumber": 350420,
    "retrievalReferenceNumber": "401010350420",
    "localTransactionDateTime": "2017-06-27T08:36:24",
    "acquiringBin": 409999,
    "acquirerCountryCode": "101",
    "senderAccountNumber": "1234567890123456",
    "senderCountryCode": "USA",
    "transactionCurrencyCode": "USD",
    "senderName": "John Smith",
    "senderAddress": "44 Market St.",
    "senderCity": "San Francisco",
    "senderStateCode": "CA",
    "recipientName": "Adam Smith",
    "recipientPrimaryAccountNumber": "4957030420210454",
    "amount": "112.00",
    "businessApplicationId": "AA",
    "transactionIdentifier": 234234322342343,
    "merchantCategoryCode": 6012,
    "sourceOfFundsCode": "03",
    "cardAcceptor": {
        "name": "John Smith",
        "terminalId": "13655392",
        "idCode": "VMT200911026070",
        "address": {
            "state": "CA",
            "county": "081",
            "country": "USA",
            "zipCode": "94105"
        }
    },
    "feeProgramIndicator": "123"
}
Response Code: 400
Headers:
x-served-by: l73c003
x-correlation-id: 1498552589_772_91_l73c003_VDP_ARM
x-backside-transport: FAIL FAIL,FAIL FAIL
x-opnet-transaction-trace: a2_59b95792-723c-4499-adbd-cc66e1742169,a2_0d676671-0d55-4e9d-8a3f-ed6401c7881e
x-app-status: 400
x-application-error-code: 3001
x-global-transaction-id: 2909673873
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=2592000;includeSubdomains
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
content-security-policy-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://
ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
x-content-security-policy-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https:
//ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
x-webkit-csp-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doublecl
ick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
content-type: application/json;charset=UTF-8
content-language: en-US
content-length: 131
x-cnection: close, close
date: Tue, 27 Jun 2017 08:36:29 GMT
connection: close
Body: {
    "errorMessage": "API Validation Error: 3001. Transaction to Recipient Card Country is restricted by the Sender Institution "
}
    1) Push Funds Transaction Test 

**## More info:** 

  2 passing (4s)
  1 failing

  1) Visa Direct Push Funds Transactions test Push Funds Transaction Test:
     Uncaught AssertionError: expected 400 to equal 200
      at Function.assert.equal (C:\Users\Admin\Desktop\VISA\vdp-node\node_modules\chai\lib\chai\interface\assert.js:126:10)
      at C:\Users\Admin\Desktop\VISA\vdp-node\test\visadirect\fundstransfertest.js:57:12
      at Request._callback (C:\Users\Admin\Desktop\VISA\vdp-node\libs\visaapiclient.js:68:4)
      at Request.self.callback (C:\Users\Admin\Desktop\VISA\vdp-node\node_modules\request\request.js:188:22)
      at Request.<anonymous> (C:\Users\Admin\Desktop\VISA\vdp-node\node_modules\request\request.js:1171:10)
      at IncomingMessage.<anonymous> (C:\Users\Admin\Desktop\VISA\vdp-node\node_modules\request\request.js:1091:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Test failed.  See above for more details.

My fundstransfertest.js file is identical to your file in repository.

What is wrong with that?
Please help.

**Comment by ankeshanand** [comment]
@YuriiZadorozhnyi We are looking into this.

**Comment by brunomazzardo** [comment]
Same problem

**Comment by Krajiyah** [comment]
Same Problem

**Comment by Krajiyah** [comment]
Same Problem

**Comment by brunomazzardo** [comment]
Hey Krajiyah, their data on this example is wrong, use the one on the reference doc that will work

**Comment by brsbilgic** [comment]
I created a PR to fix this. Thanks @brunomazzardo 
https://github.com/visa/SampleCode/pull/51

**Comment by vivek241** [comment]
Fixed with PR [#54](https://github.com/visa/SampleCode/pull/54)

**Comment by noahwalugembe** [comment]
I am getting this error friends can some one help me
(Push Funds Transaction Test Error: "Protocol {https not supported or disabled in libcurl" - Code: 1)

**Comment by vivek241** [comment]
@noahwalugembe - Can you please share the curl command that you are trying?

**Comment by noahwalugembe** [comment]
<?php

namespace Vdp;

class VisaAPIClient {

public function __construct() {
$this->conf = parse_ini_file ( "configuration.ini", true );
$this->timeout = 80;
$this->connectTimeout = 30;
}
private function loggingHelper( $response, $curl, $testInfo, $requestBody )
{
printf("%s\n",$testInfo);
if(!$response) {
printf ('Error: "' . curl_error($curl) . '" - Code: ' . curl_errno($curl));
} else {
if (empty($requestBody) == false && $requestBody != '') {
$json = json_decode($requestBody);
$json = json_encode($json, JSON_PRETTY_PRINT);
printf("Request Body : %s\n", $json);
}
$header_size = curl_getinfo($curl, CURLINFO_HEADER_SIZE);
$header = substr($response, 0, $header_size);
$body = substr($response, $header_size);
printf ("Response Status: %s\n",curl_getinfo($curl, CURLINFO_HTTP_CODE));
printf($header);
if (empty($body) == false && $body != '') {
$json = json_decode($body);
$json = json_encode($json, JSON_PRETTY_PRINT);
printf("Response Body : %s\n", $json);
}
}
}
/* Correlation Id ( ex-correlation-id ) is an optional header while making
an API call. You can skip passing the header while calling the API's. */
private function getCorrelationId() {
$seed = str_split('abcdefghijklmnopqrstuvwxyz'
                 .'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
                 .'0123456789');
shuffle($seed);
$rand = '';
foreach (array_rand($seed, 12) as $k) $rand .= $seed[$k];
return $rand."_SC";
}
private function getBasicAuthHeader($userId, $password) {
$authString = $userId.":".$password;
$authStringBytes = utf8_encode($authString);
$authloginString = base64_encode($authStringBytes);
return "Authorization:Basic ".$authloginString;
}
public function doMutualAuthCall($method, $path, $testInfo,
$requestBodyString, $inputHeaders = array()) {
$visaUrl="https://sandbox.api.visa.com/";
$cert="/cirtificate/cert.pem";
        $key="/cirtificate/key_d8c01a82-287c-40b3-9f25-bc85a1c9dda3.pem";
$curl = curl_init ();
$method = strtolower ( $method );
//$certificatePath = $this->conf ['VDP'] ['cert'];
//$privateKey = $this->conf ['VDP'] ['key'];
$certificatePath = $cert;
$privateKey = $key;
$userId = $this->conf ['VDP'] ['userId'];
$password = $this->conf ['VDP'] ['password'];
//$absUrl = $this->conf ['VDP'] ['visaUrl'].$path;
$absUrl = $visaUrl.$path;
$authHeader = $this->getBasicAuthHeader($userId, $password);
$headers = (array("Accept: application/json", $authHeader,
"ex-correlation-id: ".$this->getCorrelationId()));
if (count($inputHeaders) > 0) {
foreach ($inputHeaders as &$header) {
array_push($headers, $header);
}
}
$opts = array ();
if ($method == 'get') {
$opts [CURLOPT_HTTPGET] = 1;
} elseif ($method == 'post') {
array_push($headers, "Content-Type: application/json");
$opts [CURLOPT_POST] = 1;
$opts [CURLOPT_POSTFIELDS] = $requestBodyString;
}
$opts [CURLOPT_URL] = $absUrl;
$opts [CURLOPT_RETURNTRANSFER] = true;
$opts [CURLOPT_CONNECTTIMEOUT] = $this->connectTimeout;
$opts [CURLOPT_TIMEOUT] = $this->timeout;
$opts [CURLOPT_HTTPHEADER] = $headers;
$opts [CURLOPT_HEADER] = 1;
$opts [CURLOPT_SSLCERT] = $certificatePath;
$opts [CURLOPT_SSLKEY] = $privateKey;
curl_setopt_array ( $curl, $opts );
$response = curl_exec ( $curl );
$this->loggingHelper( $response, $curl, $testInfo, $requestBodyString );
$statusCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
curl_close ( $curl );
return $statusCode;
}
public function doXPayTokenCall($method, $baseUrl, $resource_path,
$query_string, $testInfo, $requestBodyString, $inputHeaders = array()) {
$curl = curl_init ();
$method = strtolower ( $method );
$sharedSecret = $this->conf ['VDP'] ['sharedSecret'];
$apiKey = $this->conf ['VDP'] ['apiKey'];
$time = time();
$preHashString = $time.$resource_path.$query_string.$requestBodyString;
$xPayToken = "xv2:".$time.":".hash_hmac('sha256', $preHashString,
$sharedSecret);
$headers = (array("Accept: application/json", "X-PAY-TOKEN: ".$xPayToken,
"ex-correlation-id: ".$this->getCorrelationId()));
$absUrl = $this->conf ['VDP']
['visaUrl'].$baseUrl.$resource_path.'?'.$query_string;
if (count($inputHeaders) > 0) {
foreach ($inputHeaders as &$header) {
array_push($headers, $header);
}
}
$opts = array ();
if ($method == 'get') {
$opts [CURLOPT_HTTPGET] = 1;
} elseif ($method == 'post') {
array_push($headers, "Content-Type: application/json");
$opts [CURLOPT_POST] = 1;
$opts [CURLOPT_POSTFIELDS] = $requestBodyString;
} elseif ($method == 'put') {
array_push($headers, "Content-Type: application/json");
$opts [CURLOPT_CUSTOMREQUEST] = "PUT";
$opts [CURLOPT_POSTFIELDS] = $requestBodyString;
}
$opts [CURLOPT_URL] = $absUrl;
$opts [CURLOPT_RETURNTRANSFER] = true;
$opts [CURLOPT_CONNECTTIMEOUT] = $this->connectTimeout;
$opts [CURLOPT_TIMEOUT] = $this->timeout;
$opts [CURLOPT_HTTPHEADER] = $headers;
$opts [CURLOPT_HEADER] = 1;
curl_setopt_array ( $curl, $opts );
$response = curl_exec ( $curl );
$this->loggingHelper( $response, $curl, $testInfo, $requestBodyString );
$statusCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);
curl_close ( $curl );
return $statusCode;
}


}

/////////////
$visaAPIClient = new VisaAPIClient();

$Pull = new visaAPIClient( );
$Push = new visaAPIClient( );
$strDate = date('Y-m-d\TH:i:s', time());
$baseUrl="visadirect/";
$resourcePath="fundstransfer/v1/pullfundstransactions";
$fundsTransferRequest = json_encode ( [
'systemsTraceAuditNumber' => 300259,
'retrievalReferenceNumber' => '407509300259',
'localTransactionDateTime' => $strDate,
'acquiringBin' => 409999,
'acquirerCountryCode' => '101',
'senderPrimaryAccountNumber' => '4957030100009952',
'senderCardExpiryDate' => '2020-03',
'senderCurrencyCode' => 'USD',
'amount' => '110',
'surcharge' => '2.00',
'cavv' => '0000010926000071934977253000000000000000',
'foreignExchangeFeeTransaction' => '10.00',
'businessApplicationId' => 'AA',
'merchantCategoryCode' => 6012,
'cardAcceptor' => [
'name' => 'Saranya',
'terminalId' => '365539',
'idCode' => 'VMT200911026070',
'address' => [
'state' => 'CA',
'county' => '081',
'country' => 'USA',
'zipCode' => '94404'
]
],
'magneticStripeData' => [
'track1Data' => '1010101010101010101010101010'
],
'pointOfServiceData' => [
'panEntryMode' => '90',
'posConditionCode' => '0',
'motoECIIndicator' => '0'
],
'pointOfServiceCapability' => [
'posTerminalType' => '4',
'posTerminalEntryCapability' => '2'
],
'feeProgramIndicator' => '123'
] );



/////////////////
      //http://www.qoncious.com/questions/enable-ssl-xampp-and-wampserver
      //
https://stackoverflow.com/questions/5065281/how-to-enable-ssl-in-wamp-server

//https://www.proy.info/how-to-enable-localhost-https-on-wamp-server/
//noah is the passphrase
// sending money
$values=curl_version();
echo $values["version"];
$Pull->doMutualAuthCall ( 'post', $baseUrl.$resourcePath, 'Push Funds
Transaction Test', $fundsTransferRequest );
    //$Push->doMutualAuthCall ( 'post', $baseUrl.$resourcePath, 'Push Funds
Transaction Test', $fundsTransferRequest );

?>
