### ISSUE TITLE
/cybersource/payments/v1/credits return 500

### ISSUE THREAD

**Issue by huang47** [visa/SampleCode#44]
URL : https://sandbox.api.visa.com/cybersource/payments/v1/credits?apikey=<apikey>
apikey=<apikey>
Response Code: 500
Headers:
x-served-by: l55c006
x-correlation-id: 1499202139_376_69_l55c006_VDP_ARM
x-backside-transport: FAIL FAIL,FAIL FAIL
x-global-transaction-id: 2575102215
x-app-status: 500
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=2592000;includeSubdomains
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
expires: Thu, 01 Jan 1970 00:00:00 GMT
content-security-policy-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
x-content-security-policy-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
x-webkit-csp-report-only: default-src 'self' https://*.v.me https://*.visa.com;script-src 'self' 'unsafe-inline' 'unsafe-eval'  https://*.visa.com https://*.v.me;img-src 'self' https://*.v.me https://*.visa.com https://*.unica.com https://ad.doubleclick.net;style-src 'self' 'unsafe-inline' https://*.visa.com;object-src  https://*.v.me https://*.visa.com data:;report-uri /logging/logCSPReport;
content-type: application/json;charset=UTF-8
content-language: en-US
content-length: 235
x-cnection: close, close
date: Tue, 04 Jul 2017 21:02:19 GMT
connection: close
Body: {
    "responseStatus": {
        "status": 500,
        "reason": "internal_server_error",
        "message": "Request failed due to unknown system error.",
        "correlationId": "3ce6c822-75be-4f14-bbc9-a1fd06792e7a",
        "details": []
    }
}

**Comment by ankeshanand** [comment]
@huang47 We are looking into it.

**Comment by huang47** [comment]
@ankeshanand thank you!

**Comment by ankeshanand** [comment]
@huang47 Can you provide the details regarding your API call? i.e. the Payload and headers that you were trying to send? Also, which language's SDK were you using?

**Comment by huang47** [comment]
it's vdp-node 

I created following test script and run it

```
var config = require('../../config/configuration.json');
var VisaAPIClient = require('../../libs/visaapiclient.js');

var visaAPIClient = new VisaAPIClient();
var body = '';

var baseUri = 'cybersource/';
var resourcePath = 'payments/v1/credits';
var queryParams = `apikey=${config.apiKey}`;
visaAPIClient.doXPayRequest(baseUri, resourcePath, queryParams, body, 'POST', {}, 
function(err, responseCode) {
  console.log(err, responseCode);
});
```

**Comment by huang47** [comment]
I might look at the wrong API, I was trying to retrieve all credit card application offers though.

Fwiw if I changed `body` from '' to `{}` which returns `400` where missing fields in the payload doesn't seem necessary in `/cybersource/payments/v1/credits` according to [documentation](https://developer.visa.com/products/cybersource/reference#cybersource__cybs__v1__retrieve_all_credits)

```
var config = require('../../config/configuration.json');
var VisaAPIClient = require('../../libs/visaapiclient.js');

var visaAPIClient = new VisaAPIClient();
// change this from '' to {} 
var body = JSON.stringify({});

var baseUri = 'cybersource/';
var resourcePath = 'payments/v1/credits';
var queryParams = `apikey=${config.apiKey}`;
visaAPIClient.doXPayRequest(baseUri, resourcePath, queryParams, body, 'POST', {}, 
function(err, responseCode) {
  console.log(err, responseCode);
});
```

```
Body: {
    "responseStatus": {
        "status": 400,
        "reason": "missing_field",
        "message": "Required field(s) is missing from the request.",
        "correlationId": "8d26b82f-a3f2-4f25-bc27-e2f60fae1b67",
        "details": [
            {
                "location": "payment.cardNumber"
            }
        ]
    }
}

**Comment by ankeshanand** [comment]
Hi @huang47, The API you linked is a GET endpoint, but you are making a POST call, and that's why it's expecting additional request parameters.

That aside, the Cybersource product doesn't seem to correspond to your use-case. It's meant for merchants to capture payments. There's a different product that deals with Credit card offers: https://developer.visa.com/products/vop. I have also asked a representative from VDP to reach out to you in case you need further clarification regarding which product/API to use.

**Comment by huang47** [comment]
@ankeshanand thanks! it's working for me after changing the method from POST to GET

Also, may I know what's the API for credit card offer? VOP looks like the API to provide offers to card holders. Any ideas where I can find the API for new credit card application offers? Thanks

**Comment by ankeshanand** [comment]
@huang47 Not that I am aware of, but you should be able to get better answers from our product team representatives. I think someone already reached out to you via email, feel free to shoot them any questions that you may have!

**Comment by vivek241** [comment]
Hi @huang47,

It seems like this issue is fixed. Can you please close this issue?
Also, I hope you've got the information you were looking for about the offers. If not, please let us know.

Thanks,
Vivek
