### ISSUE TITLE
The SDK influences every array in the page

### ISSUE THREAD

**Issue by cozohar** [visa/SampleCode#45]
Hello,

In the last few days, you changed something in your SDK that influences the arrays in the page.
This code adds contains function to every array:
**Array.prototype.contains=function(a){for(i in this)if(this[i]==a)return!0;return!1};**

We used for(i in array) and we saw the array suddenly contains another object.

![image](https://user-images.githubusercontent.com/24695665/29418466-0b21e584-8375-11e7-869a-5902f79587e5.png)

**Comment by louisptremblay** [comment]
Having the same problem, this has the potential to break a lot of websites

Visa, if you really need a function on Array prototype, you need to set enumerable: false
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by ankeshanand** [comment]
@cozohar and @louisptremblay, Thanks for reporting the issue. We have informed the Visa Checkout team regarding the same.

**Comment by thomaspurves** [comment]
@ankeshanand @cozohar @loisptremblay thanks for taking the time to provide a detailed report, the Visa Checkout team has a fix tested and will be patched shortly.

**Comment by vivek241** [comment]
@cozohar @louisptremblay This issue has been fixed in the latest version (5.6.0) of the SDK.
https://sandbox-assets.secure.checkout.visa.com/checkout-widget/resources/js/integration/v1/sdk.js
