### ISSUE TITLE
Internal Application Error

### ISSUE THREAD

**Issue by vasylmalanchak** [visa/SampleCode#47]
For Merchant Search(https://sandbox.api.visa.com/merchantsearch/v1/search) I'm always getting error:
"status": {
     "statusDescription": "Internal Application Error",
     "statusCode": "CDI082"
}
I tried it from visa website(https://developer.visa.com/capabilities/merchant_search/reference#merchant_search__merchant_search)
and from my java code(with sample code provided)).
 
I need to search by two fields: acquirerCardAcceptorId and acquiringBin.
I also tried with Test Data from Merchant Search application but getting error "Invalid Group Name{GNBANKA}".
If change responseAttrList to "GNSTANDARD" I'm getting error "Internal Application Error"

**Comment by vivek241** [comment]
Hi @vasylmalanchak ,

I was able to get a valid response with the below payload. This is with the data from the Test Data section.
```
{
	"searchAttrList": {
		"acquirerCardAcceptorId": "424295031886",
		"acquiringBin": "476197"
	},
	"responseAttrList": [
		"GNSTANDARD"
	],
	"header": {
		"requestMessageId": "Request_001",
		"startIndex": "0",
		"messageDateTime": "2017-11-06T11:11:07.903"
	}
}
```

**Comment by vasylmalanchak** [comment]
Hi vivek241,
Yes It fixed now.
https://community.developer.visa.com/t5/Visa-Developer-Capabilities/Internal-Application-Error/td-p/6830

**Comment by vivek241** [comment]
@vasylmalanchak Good to know :)
Can you please close the issue?
