### ISSUE TITLE
Expected input credentials were not present

### ISSUE THREAD

**Issue by omaidf** [visa/SampleCode#49]
Hopefully I'll get some better support on Github. I'm receiving the following error:
{"responseStatus":{"code":"9123","severity":"ERROR","info":"","status":401,"message":"Expected input credentials were not present"}}

Code is the following:

	creds = "[REDACTEDUSERNAME]:[REDACTEDPASS]"
	headers = {"Authorization": "%s" % base64.b64encode(creds), "Accept": "application/json"}
	url = "https://sandbox.api.visa.com/vti/v1/getioc?startDate=2017-10-01&endDate=2017-10-25"
	r = requests.get(url,cert=('/Users/[REDACTED]/Desktop/visa/cert.pem','/Users/[REDACTED]/Desktop/visa/key.pem'),headers=headers)
	print r.content

**Comment by vivek241** [comment]
Hi Omaid,

The Authorization header should be in the below format
```
Authorization: Basic <base64encoded username:password>
```
It seems like the 'Basic' part is missing.

In the response you should see a header named 'X-CORRELATION-ID'. Can you please share the value of that header? That would help us in debugging the issue further.

**Comment by omaidf** [comment]
Vivek, that solved the issue. You are amazing! Thank you.
