### ISSUE TITLE
java.net.SocketException: Connection reset on Linux

### ISSUE THREAD

**Issue by klevis** [visa/SampleCode#50]
Hi,
I am using vdp-java client and it works fine on windows but when I execute the application from linux server it fails with above general exception.

I simply moved JKS file from windows to linux folder but also tried to generate JKS on linux and still getting the same error.

Any idea?

Thank you,
Klevis

**Comment by vivek241** [comment]
Hi @klevis,

Ideally the same JKS file should work fine on Linux as well.

Are you able to do a curl to https://sandbox.api.visa.com from the Linux server?

Thanks,
Vivek

**Comment by klevis** [comment]
Hi @vivek241 
I tried and i get
curl: (35) SSL connect error

Thanks for support ,
Klevis

**Comment by klevis** [comment]
I run also like below:
curl -E ./myapp_keyAndCertBundle.jks https://sandbox.api.visa.com
and than I get 
curl: (58) Unable to load client cert -8018.

feel free to suggest option for running curl..
Klevis

**Comment by vivek241** [comment]
Hi @klevis ,

Can you check the curl version?
https://stackoverflow.com/questions/19265100/curl-command-unable-to-load-client-cert-8018

Thanks,
Vivek

**Comment by klevis** [comment]
Hi ,
I followed the instructions described and I am able to see cert on DB:
```
 certutil -L -d /home/a.kramo/nss

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

1                                                            u,u,u
```

But than I get the following error:
```
 curl -vk --cert "1" https://sandbox.api.visa.com
* About to connect() to sandbox.api.visa.com port 443 (#0)
*   Trying 23.45.100.192... connected
* Connected to sandbox.api.visa.com (23.45.100.192) port 443 (#0)
* Initializing NSS with certpath: sql:/home/a.kramo/nss
* warning: ignoring value of ssl.verifyhost
* NSS error -5961
* Closing connection #0
* SSL connect error
curl: (35) SSL connect error
```

**Comment by vivek241** [comment]
@klevis - Can you try curl with the key (--key) and cert (--cert) separately?

**Comment by klevis** [comment]
Hi @vivek241
 I tried like below but still error 

> curl --key key.pem --cert cert.pem https://sandbox.api.visa.com
> curl: (35) SSL connect error

In you knowledge was the code tested on Linux with same JKS?

**Comment by vivek241** [comment]
Hi @klevis ,

Not sure if it the code was tested on Linux.
I'm trying to run it myself on Linux. Will let you know the results.

**Comment by klevis** [comment]
Hi @vivek241 
Finally is working now. The problem was rather with some black list firewall list not allowing the application to connect.
Anyway thank you very much for your great support.
